# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build-master:
  stage: build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - export base_image_ver=$(grep FROM Dockerfile|cut -d ':' -f2|tail -1)
    - export pgis_ver=$(grep POSTGIS_VER Dockerfile|cut -d '=' -f2|head -1)
    - export image_name="$CI_REGISTRY_IMAGE/stolon"
    - export image_tag="$base_image_ver-pgis$pgis_ver-RC"
  script:
    - docker build --pull -t "$image_name" .
    - docker tag "$image_name" "$image_name:$image_tag"
    - docker push "$image_name"
    - docker push "$image_name:$image_tag"
  only:
    - master

build-tags:
  stage: build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - export base_image_ver=$(grep FROM Dockerfile|cut -d ':' -f2|tail -1)
    - export pgis_ver=$(grep POSTGIS_VER Dockerfile|cut -d '=' -f2|head -1)
    - export image_name="$CI_REGISTRY_IMAGE/stolon"
    - export image_tag="$base_image_ver-pgis$pgis_ver"
  script:
    - docker build --pull -t "$image_name:$image_tag" .
    - docker push "$image_name:$image_tag"
  only:
    - tags

build-branches:
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - export base_image_ver=$(grep FROM Dockerfile|cut -d ':' -f2|tail -1)
    - export pgis_ver=$(grep POSTGIS_VER Dockerfile|cut -d '=' -f2|head -1)
    - export image_name="$CI_REGISTRY_IMAGE/stolon"
    - export image_tag="$base_image_ver-pgis$pgis_ver-$CI_COMMIT_REF_SLUG"
  script:
    - docker build --pull -t "$image_name:$image_tag" .
    - docker push "$image_name:$image_tag"
  except:
    - master
    - tags

